name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Install Dependencies
      run: |
        npm install
        cd client && npm install
        cd ../server && npm install
        
    - name: Build React App
      run: |
        cd client
        npm run build
        
    - name: Test
      run: |
        cd client
        npm test -- --passWithNoTests
